### ISSUE TITLE
拍照能不能直接返回？

### ISSUE THREAD

**Issue by jygsdjflsd** [imuhao/RxPicker#14]
拍照之后还需要选择才能返回，能不能直接返回？

**Comment by imuhao** [comment]
是可以支持的  需要自己修改下逻辑

**Comment by jygsdjflsd** [comment]
修改PickerFragment的handleCameraResult()直接返回么？还是有接口？

**Comment by imuhao** [comment]
> 修改PickerFragment的handleCameraResult()直接返回么？还是有接口？

是的,直接调用返回的就好了
