### ISSUE TITLE
能不能兼容下Rxjava1

### ISSUE THREAD

**Issue by luhuanxml** [imuhao/RxPicker#3]
之前一直用你这个框架，现在我们项目集成了bomb，默认必须添加rxjava1，不能再用rxjava2了，这个框架就用不了了。

**Comment by imuhao** [comment]
这个是不行的, 因为 RxJava 1和2 是不能相互兼容

**Comment by luhuanxml** [comment]
我拷贝了你的项目，然后将所有的rxjava2改为了rxjava1.发布到了我自己的githgub上面，希望你不要介意。

**Comment by imuhao** [comment]
可以的
