### ISSUE TITLE
android webview打开相册选择图片不能直接返回

### ISSUE THREAD

**Issue by tangchuanyong** [imuhao/RxPicker#4]
android webview中正常选择图片没有问题,但是如果进入选择相册页面不做选择,直接点击返回的话.再次点击webview上的按键将无法再次打开相册页面.这个是什么问题!

**Comment by luhuanxml** [comment]
我觉得是这样的，选择图片后回去webview有刷新，直接点击返回web view没有刷新，你要不要把load webview做到onstart中。

**Comment by tangchuanyong** [comment]
不是这个问题,是因为不管成功还是失败都必须给这个方法onReceiveValue()设置值,没有选择的话就直接传null,如果不设置的话就会导致二次点击无法调起相册.RxPicker在resultCode != RESULT_OK的情况下没做处理,所以没走回调方法导致的!

**Comment by luhuanxml** [comment]
喔，这个是用subscribe返回数据的

**Comment by AL-bruce** [comment]
> onReceiveValue

这个在哪里设置呢，进入相册没有选择，点击返回以后就不能再唤起相册
