### ISSUE TITLE
同一个页面存在几个ImageView点击第一个ImageView选择图片,存在打开相册不做选择直接返回,然后点击第二个ImageView选择图片,此时发生第一个ImageView和第二个Imageview同时显示第二次选择的图片.

### ISSUE THREAD

**Issue by tangchuanyong** [imuhao/RxPicker#5]

**Comment by firefly5927** [comment]
大兄弟，你这部分代码提交那里去了？

**Comment by tangchuanyong** [comment]
在ResultHandlerFragment中的@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (resultCode != Activity.RESULT_OK) {//取消不做选择
            resultSubject.onNext(RxPickerManager.getInstance().getResultCanceled());
        }else{
            if (requestCode == REQUEST_CODE && data != null) {
                resultSubject.onNext(RxPickerManager.getInstance().getResult(data));
            }
        }

    }

**Comment by tangchuanyong** [comment]
public List<ImageItem> getResultCanceled() {
    return new ArrayList<ImageItem>();
  }

**Comment by tangchuanyong** [comment]
我做的处理的是不管是选择还是未做选择都返回结果了！就是直接返回的话，直接返回一个空集合！需要自己加个判断！我这边有适配webview中的照片选择！不返回有bug。
RxPicker.of().start(MeActivity.this).subscribe(imageItems -> {
            if (imageItems != null && imageItems.size() > 0) {
              
            }
        });

**Comment by firefly5927** [comment]
嗯。

**Comment by firefly5927** [comment]
嗯。你把代码提交上去吧。我加上后就正常了。

**Comment by firefly5927** [comment]
[https://github.com/imuhao/RxPicker/issues/5](url)
