### ISSUE TITLE
调起相机拍照,选择图片成功后,再次调起相册,返现有两张一样的刚刚拍摄的照片!

### ISSUE THREAD

**Issue by tangchuanyong** [imuhao/RxPicker#7]

**Comment by tangchuanyong** [comment]
是不是在拍照后又创建了一张图片！

**Comment by imuhao** [comment]
请描述清楚一点, 我刚刚试了一下没有问题

**Comment by tangchuanyong** [comment]
调起相册选择，拍照，返回后选择刚刚拍的照片。正常返回！再次调起相册选择，发现刚刚拍摄的照片有两张！

**Comment by firefly5927** [comment]
me too

**Comment by firefly5927** [comment]
我这里用手机拍照后也是两张照片，我看了下。我看一个是存放在Camera，另一个是存放在camera里面的。

**Comment by firefly5927** [comment]
我这里用手机拍照后也是两张照片，我看了下。我看一个是存放在Camera，另一个是存放在camera里面的。自己处理了一下。

**Comment by tangchuanyong** [comment]
你怎么修改的？

**Comment by firefly5927** [comment]
PickerFragmentPresenter这个类里面
private Observable<List<ImageFolder>> loadAllFolder(final Context context) {
...
String bucketName = cursor.getString(5);
if(TextUtils.equals(bucketName,"camera")){
                continue;
            }
...
加了这句话

**Comment by SmallWinter** [comment]
应该是遇到同样问题，调起之后不选择退出，再次调起选择之后回调方法会调两次；且已经做过调试，前面几次未选择回调方法就会调几次    + 1（最后选择的那次）。

**Comment by tangchuanyong** [comment]
列表获取数据的时候获取了两次，不知道怎么回事。if(TextUtils.equals(bucketName,"camera")){
continue;
}这样确实可以解决问题。有两个camera，一个大写开头，一个小写开头的。导致获取了两张同样的图片。过滤掉一个就好了。

**Comment by SmallWinter** [comment]
lssues我可能描述不是很清楚，跟拍照没关系；主要是选择图片问题，第一步：调起图片选择器，不做选择，返回；第二步，再调起，假设选一张，确认，这时候回调方法会出发两次（正常应该是只触发一次）！
 而且，上面的第一步做的次数越多，做第二步的时候触发回调方法的次数为：（第一步次数 + 1） 次！

**Comment by tangchuanyong** [comment]
并不会触发两次，我做了修改，不做选择取消的时候我也做了处理！所以只要调起，不管选不选都会走完一整个流程，这个是我在同一个页面存在多个图片需多次选择照片的时候就改了！

**Comment by SmallWinter** [comment]
![image](https://user-images.githubusercontent.com/8638180/33755591-74a1609c-dc2c-11e7-9199-8f5b0bc34fb7.png)
这是代码部分，版本也十分确定用的最新版1.1.5；我debug调试的，确实是存在有这样的问题，烦请大佬确认一下！（备注：测试机型，红米3s，等下我再用其他机型测试）
应是存在这样的问题，用另外的两款华为机型也是如此！

**Comment by firefly5927** [comment]
[https://github.com/imuhao/RxPicker/issues/5](url) 这里面有解决办法。
